all:
  hosts:
    master-1:
      ansible_host: 10.0.1.24
      ip: 10.0.1.24
      access_ip: 10.0.1.24
    master-2:
      ansible_host: 10.0.1.6
      ip: 10.0.1.6
      access_ip: 10.0.1.6
    master-3:
      ansible_host: 10.0.1.34
      ip: 10.0.1.34
      access_ip: 10.0.1.34
    worker-1:
      ansible_host: 10.0.1.18
      ip: 10.0.1.18
      access_ip: 10.0.1.18
    worker-2:
      ansible_host: 10.0.1.19
      ip: 10.0.1.19
      access_ip: 10.0.1.19
    worker-3:
      ansible_host: 10.0.1.3
      ip: 10.0.1.3
      access_ip: 10.0.1.3
    worker-4:
      ansible_host: 10.0.1.22
      ip: 10.0.1.22
      access_ip: 10.0.1.22
  children:
    kube_control_plane:
      hosts:
        master-1:
        master-2:
        master-3:
    kube_node:
      hosts:
        worker-1:
        worker-2:
        worker-3:
        worker-4:
    etcd:
      hosts:
        master-1:
        master-2:
        master-3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}