apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-access-control
  namespace: netology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: access-control
  template:
    metadata:
      labels:
        app: access-control
    spec: 
      containers:
      - name: nginx-access-control
        image: nginx:1.26