apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-logs-binding
  namespace: netology
subjects:
  - kind: User
    name: user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: view-logs
  apiGroup: rbac.authorization.k8s.io