apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: view-logs
  namespace: netology
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]