apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-{{ include "netology-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: multitool-{{ include "netology-app.fullname" . }}
  template:
    metadata:
      labels:
        app: multitool-{{ include "netology-app.fullname" . }}
    spec:
      containers:
      - name: multitool-{{ include "netology-app.fullname" . }}
        image: "{{ .Values.multitool.image.repository }}:{{ .Values.multitool.image.tag }}"
        ports:
          - containerPort: {{ .Values.multitool.image.port }}
            protocol: TCP
        env: 
          - name: HTTP_PORT
            value: "{{ .Values.multitool.image.env.HTTP_PORT }}"      