version: '3.9'
services:
  els-hot:
    image: elasticsearch:8.12.2
    container_name: els-hot
    environment:
      - node.name=els-hot
      - cluster.name=els-cluster
      - cluster.initial_master_nodes=els-hot, els-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - xpack.security.enabled=false
      - discovery.seed_hosts=els-hot,els-warm
      - node.roles=master,data_content,data_hot
      - discovery.type=multi-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elsdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - els-warm
    networks:
      - elknet

  els-warm:
    image: elasticsearch:8.12.2
    container_name: els-warm
    environment:
      - node.name=els-warm
      - cluster.name=els-cluster
      - cluster.initial_master_nodes=els-hot,els-warm
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - xpack.security.enabled=false
      - discovery.seed_hosts=els-hot,els-warm
      - node.roles=master,data_warm
      - discovery.type=multi-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elsdata2:/usr/share/elasticsearch/data
    networks:
      - elknet

  logstash:
    image: logstash:8.12.2
    container_name: logstash
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
    volumes:
      - ./config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - 5044:5044
    depends_on:
      - els-hot
      - els-warm
    networks:
      - elknet    

  kibana:
    image: kibana:8.12.2
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://els-hot:9200
      ELASTICSEARCH_HOSTS: '["http://els-hot:9200","http://els-warm:9200"]'
    depends_on:
      - els-hot
      - els-warm
    ports:
      - 5601:5601
    networks:
      - elknet

  filebeat:
    image: elastic/filebeat:8.12.2
    container_name: filebeat
    privileged: true
    user: root
    command: filebeat -e -strict.perms=false
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker:/var/lib/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - logstash
    networks:
      - elknet

  some_application:
    image: library/python:3.9-alpine
    container_name: some_app
    volumes:
      - ./pinger/:/opt/
    entrypoint: python3 /opt/run.py

volumes:
  elsdata1:
    driver: local
  elsdata2:
    driver: local              

networks:
  elknet:
    driver: bridge