apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: netology2
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - name: wait-for-service
        image: busybox:latest
        command: ['sh', '-c', 'until nslookup nginx-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for service; sleep 2; done;']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80