all:
  hosts:
    master-1:
      ansible_host: 51.250.3.29
      ip: 10.0.1.24
      access_ip: 51.250.3.29
    master-2:
      ansible_host: 158.160.52.37
      ip: 10.0.1.6
      access_ip: 158.160.52.37
    master-3:
      ansible_host: 158.160.107.65
      ip: 10.0.1.34
      access_ip: 158.160.107.65
  children:
    kube_control_plane:
      hosts:
        master-1:
        master-2:
        master-3: