{
 "title": "for netology homework",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Утилизация CPU для nodeexporter (в процентах, 100-idle)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "Утилизация CPU для nodeexporter (в процентах, 100-idle)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "Общее количество RAM" },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Количество свободной RAM" }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(node_load1{job=\"node\"})",
     "legendFormat": "Среднее время нагрузки на CPU за последнюю 1 минуту"
    },
    {
     "expr": "avg(node_load5{job=\"node\"})",
     "legendFormat": "Среднее время нагрузки на CPU за последние 5 минут"
    },
    {
     "expr": "avg(node_load15{job=\"node\"})",
     "legendFormat": "Среднее время нагрузки на CPU за последние 15 минут"
    }
   ]
  },
  {
   "title": "File System",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "node_filesystem_avail_bytes", "legendFormat": "Объём доступного пространства" },
    { "expr": "node_filesystem_size_bytes", "legendFormat": "Объём раздела" }
   ]
  }
 ]
}