apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-task-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-1
  template:
    metadata:
      labels:
        app: task-1
    spec:
      nodeSelector:
         kubernetes.io/hostname: anikeev    
      containers:
      - name: busybox
        image: busybox:latest
        command: ['sh', '-c', 'mkdir -p /shared && while true; do echo "$(date) - Test message every 5 seconds." >> /shared/log.txt; sleep 5; done']
        volumeMounts:
        - name: fs
          mountPath: /shared
      - name: multitool
        image: wbitt/network-multitool
        volumeMounts:
        - name: fs
          mountPath: /shared
      volumes:
      - name: fs
        persistentVolumeClaim:
          claimName: local-claim